theme: jekyll-theme-minimal

title: "教会関連"
description: "教会関連の資料置き場"
logo: img/icon.gif
timezone: Asia/Tokyo

# build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock

# plugins
plugins:
  - jemoji
